### ISSUE TITLE
Add twitter api error codes

### ISSUE THREAD

**Issue by arzzen** [arzzen/all-exit-error-codes#7]

**Comment by antimatter96** [comment]
There are plenty of Twitter APIs : 

> The REST APIs provide programmatic access to read and write Twitter data. Author a new Tweet, read author profile and follower data, and more.
> 
> If your intention is to monitor or process Tweets in real-time, consider using the Streaming API instead.
> 
> Ads API

Which one should I do ? Currently starting with the first one

**Comment by arzzen** [comment]
OK, i agree
